### ISSUE TITLE
Should we remove IGitt from tests?

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/python#244]
https://github.com/thoth-station/python/blob/da533887769c7e3c44c5c935bdd7017909a7cf13/tests/test_package_version.py#L102

**Comment by fridex** [comment]
I think the test checks if we raise an appropriate error if a git version of a package is used. Is there any reason why you would like to remove it?

**Comment by saisankargochhayat** [comment]
Makes sense, I will close this.
