### ISSUE TITLE
Deliver Missing Module

### ISSUE THREAD

**Issue by harshad16** [thoth-station/python#370]
Hey, AICoE-CI!

Please deliver the package module for the following tag, as it missing on PyPI:

Tag: v0.15.3

**Comment by pacospace** [comment]
isn't it already on PyPi: https://pypi.org/project/thoth-python/ @harshad16

**Comment by harshad16** [comment]
i just see version v0.15.2 in pypi

**Comment by pacospace** [comment]
![Screenshot from 2021-02-25 15-46-47](https://user-images.githubusercontent.com/27498679/109170023-b1f3db80-7780-11eb-8064-c9e40ea2e454.png)
