### ISSUE TITLE
Kebechet Advise

### ISSUE THREAD

**Issue by codificat** [thoth-station/python#469]
Hey, Kebechet!

Update my dependencies, please.

Not what you did in #467. Now for real, please.

**Comment by codificat** [comment]
Boom again: https://github.com/thoth-station/support/issues/207

**Comment by codificat** [comment]
Also https://github.com/thoth-station/support/issues/208

**Comment by goern** [comment]
all dependent issues closed, closing this on too. feel free to re-open
/close
